### ISSUE TITLE
Allow configuring default storage class

### ISSUE THREAD

**Issue by K1Hyve** [phidatalab/RADAR-K8s-Infrastructure#15]
Currently default storage class in the cluster is gp2 and it's not configurable. It would be good to make it configurable during the installation, I saw some suggestions to change the class manually after the cluster creation but that wouldn't be ideal, especially that it's not something that we can add to the RADAR-Kubernetes. I didn't find an easy way to change the default setting with the current modules that are being used, so more investigation might be needed.

**Comment by baixiac** [comment]
Agreed but that largely depends on what [aws-ebs-csi-driver](https://github.com/kubernetes-sigs/aws-ebs-csi-driver) can provide. At then, we had to do manual configuration on things like reclaim policy, EBS volume resizeablity and so on post volume creation. It is time to revisit the latests features and see if they have done any improvement.

**Comment by baixiac** [comment]
Looks like this is still not supported by the addon configuration at present. Hence, this PR https://github.com/phidatalab/RADAR-K8s-Infrastructure/pull/17, which creates storage classes for all SSD volume types supported by EKS. 
* radar-base-ebs-sc-gp2
* radar-base-ebs-sc-gp3
* radar-base-ebs-sc-io1

The users can refer to the desired one when configuring `storageClass` of PVCs in RADAR charts. Alternatively, they can change the global default to one of the above by`kubectl edit` the gp2 and the desired one and alter the values of the `storageclass.beta.kubernetes.io/is-default-class` annotations to "false" and "true" respectively.

**Comment by baixiac** [comment]
Addressed by https://github.com/phidatalab/RADAR-K8s-Infrastructure/pull/17. The default storage class is now set to `radar-base-ebs-sc-gp2`.
