### ISSUE TITLE
Use cluster name for resource creation

### ISSUE THREAD

**Issue by K1Hyve** [phidatalab/RADAR-K8s-Infrastructure#3]
S3 bucket names should be globally unique, values commonly used in `${var.environment}` such as `dev` and `prod` won't be unique.

**Edit:** `${var.environment}` is used in other places as well. I think its description and examples can be improved to suggest that it's name of the environment in general and not whether it's dev or prod. Or the value to be merged with `${var.eks_cluster_name}`.

**Comment by baixiac** [comment]
Alright, I can make `${var.eks_cluster_name}` part of the names of the resources such as S3 buckets. The naming was based on the assumption that only one Radar K8s cluster would be created for each environment. And let's also not go down into the rabbit hole that multiple clusters could share the same bucket.

**Comment by K1Hyve** [comment]
Thanks! What do mean as environment? The AWS region or the `environment` variable?
I don't think multiple clusters can use the same bucket since it will mess up the data processing and potentially corrupt it.

**Comment by K1Hyve** [comment]
I see, in our use case at least, it's possible to have multiple clusters for different customers.

> Generally speaking that's true but every so often `int` wants to pull `test` data to do some sanity check and `test` wants to pull live data (read-only access) to replicate a bug in `prod`. I think this is on a per-user/business basis.

Fair enough, I think that would be a manual and one in a while process and not a continuous bucket sharing of a 2 different prod clusters.

**Comment by baixiac** [comment]
Indeed, continuous bucket sharing probably needs prefixes for organising objects belonging to different clusters.

The ${var.environment} is now removed from resource names and only used in DNS names and as cost-allocation tags.  https://github.com/phidatalab/RADAR-K8s-Infrastructure/pull/7

**Comment by baixiac** [comment]
Closed by #7.
